import {
    Code2,
    Database,
    Globe,
    Server,
    Smartphone,
    Cloud,
    Shield,
    Zap,
    Users,
    Clock,
    Award,
    Mail,
    MapPin,
    Briefcase,
    Layers,
    GitBranch,
    Terminal,
    Cpu,
    MonitorSmartphone,
    Palette,
    Settings,
    HeartHandshake,
    CloudCogIcon,
    Grab,
    GitGraph,
    Webhook,
    SoapDispenserDroplet,
    SoapDispenserDropletIcon,
    WandSparkles,
    AppleIcon,
    ShoppingCart
} from "lucide-react";

export const iconRegistry: Record<string, any> = {
    Code2,
    Database,
    Globe,
    Server,
    Smartphone,
    Cloud,
    Shield,
    Zap,
    Users,
    Clock,
    Award,
    Mail,
    MapPin,
    Briefcase,
    Layers,
    GitBranch,
    Terminal,
    Cpu,
    MonitorSmartphone,
    Palette,
    Settings,
    HeartHandshake,
    CloudCogIcon,
    Grab,
    GitGraph,
    Webhook,
    SoapDispenserDroplet,
    SoapDispenserDropletIcon,
    WandSparkles,
    AppleIcon,
    ShoppingCart
};

export const getIcon = (name: string) => {
    // Default to 'Layers' if icon not found
    return iconRegistry[name] || Layers;
};
